# UPDATED FEB 2026: Classify bgcArgo and SOCAT (P1-processed) using core clustering results (P2-clustered)

- Remove SIZ here
Save outputs in P2-clustered/

In [1]:
from importlib import reload
import mod_loading as loader
import mod_pcm
import datetime 
from datetime import datetime
import xarray as xr
import pandas as pd

In [2]:
import numpy as np

import figs_pcm


import mod_preprocessing as mod_prep
import mod_regression as mod_reg
import mod_pcm

In [10]:
### SET NOTEBOOK RUN PARAMETERS ### ===================

n_pca = 8               # PC components 
n_gmm = 6               # GMM classes 
dbar_limit = 501        # Depth limit for PCA 

# ================================================

# use_preprocessed = False # Set to True if you want to load pre-centered data 
save_run = True

pcm_params = 'pc' + str(n_pca) + '_gmm' + str(n_gmm)
save_path = '../working-vars/regression/P2-clustered/' + pcm_params + '/'
datetag = datetime.now().strftime('%Y%m%d') # For filenames

# Add GMM probabilities and clustering assignments to the ML inputs

In [3]:
# moved to mod_pcm
# def add_class_assignments(platDF, PCM_finder, n_gmm, profid_col='nearest_profid'):
#     """ 
    
#     @param  profid_col: 'profid' for floatDF, 'nearest_profid' for shipDF 
#             PCM_finder: dataframe with profid as index and columns for each class probability and 'class_assign' for assigned class

#             [Y_gmm, allprobs] = loader.import_p2_clustered(pcm_params = pcm_params)
#             PCM_finder = allprobs.set_index('profid') # temp object to search
#             PCM_finder['class_assign'] = Y_gmm.loc[PCM_finder.index, 'class']

#     """
#     platDF = platDF.copy()
#     for k in range(1, n_gmm+1):
#         platDF['class' + str(k) + '_prob'] = platDF[profid_col].apply(lambda x: PCM_finder.loc[x, str(k)] if x in PCM_finder.index else np.nan)
#     platDF['class_assign'] = (platDF[profid_col].apply(lambda x: PCM_finder.loc[x, 'class_assign'] if x in PCM_finder.index else np.nan))
#     # platDF['prof_datetag'] = platDF['prof_datetag'].astype(str)

#     # platDF = platDF.dropna(subset=['class_assign'])
#     # print('Initial classes assigned. Filling missing values where adjacent classes match...')

# #     # Fill in missing  cluster values where we can -- 
# #     # look for same float, profiles within +/- 11 days
# #     # If cluster was same before and after, assign to that cluster

    
#     return platDF

In [ ]:
# # moved to mod_pcm
# def fill_missing_float_classes(argoDF):
#     """ for soccom 20 m aves
#     doesn't work for shipDF yet"""
#     # argoDF['prof_datetag'] = argoDF['prof_datetag'].astype(str)
#     # argoDF['datetime'] = pd.to_datetime(argoDF['datetime'])

#     # argoDF = argoDF.set_index('profid')
#     argoDF_nona = argoDF.dropna(subset='class_assign')
#     missing = argoDF[argoDF.class_assign.isna()].reset_index()
#     available_prof_datetags = argoDF_nona.prof_datetag.unique().astype(str)
#     print('Initially missing class assignments for ' + str(len(missing)) + ' profiles, searching to fill with adjacent datetags...')

#     profsReplaced = []

#     for ind, tag in enumerate(missing.profid.unique()):
#         obs = missing.iloc[ind, :]
#         same_float = argoDF_nona[argoDF_nona.wmoid==obs.wmoid].copy()

#         if len(same_float)>0:
#             same_float.loc[:,'timediff'] = same_float.apply(lambda row: abs((row.datetime - (obs.datetime)).days), axis=1)
#             valid = same_float[same_float.timediff<12]
#             if valid.class_assign.nunique() == 1:
#                 argoDF.loc[tag, 'class_assign'] = valid.class_assign.values[0]
#                 profsReplaced = profsReplaced + [tag]

#     argoDF = argoDF.dropna(subset='class_assign')
#     print('Filled in ' + str(len(profsReplaced)) + ' missing assignments using adjacent profiles; total ' + str(len(argoDF)) + ' valid profiles')

#     return argoDF

In [ ]:
# bgcDS_test['profid'] = bgcDS_test['profid'].apply(lambda x: x.replace('id', 'testid'))

# temp = bgcDS_test.to_dataframe().reset_index().copy()
# temp['profid'] = temp['profid'].apply(lambda x: x.replace('id', 'testid'))
# bgcDS_test_updated = temp.set_index(['profid', 'pressure']).to_xarray()
# bgcDS_test_updated.assign_coords()

ValueError: the first argument to .assign_coords must be a dictionary

In [ ]:
# [coreDS, coreINDEX] = loader.import_core_data(type='processed') # has adt, sla, mld, pco2

# Import PCM results from 2.1

In [33]:
# ====== New version from feb 11 with import p2 data
[bgcArgo_trainval, bgcArgo_test, socat_trainval, socat_test, coreArgo_application] = loader.import_p1_processed()

[PCM_components, PCM_finder] = loader.import_p2_clustered(type='pcm_probs', pcm_params = pcm_params)

Importing processed dataframes...
Returned [bgcArgo_trainval(2014-2023), bgcArgo_test(2024), socat_trainval(2014-2023), socat_test(2024), coreArgo_application(2014-2023)]
Importing clustering results for pc8_gmm6...
Returned [PCM_components, PCM_finder (probabilities)]
Returned [bgcArgo_trainval(2014-2023), bgcArgo_test(2024), socat_trainval(2014-2023), coreArgo_application(2014-2023)]

In [ ]:
# [coreDS, coreINDEX] = loader.import_core_data(type='processed') # has adt, sla, mld, pco2
# [coreDS_test, coreINDEX_test] = loader.import_core_data(type='2024') # for testing with socat 2024 data, has adt, sla, mld, pco2
# # [coreDS, _] = loader.import_core_data(type='L3_extended') # now includes core 2024 data for potential testing

# [bgcDS_test, bgcINDEX_test] = loader.import_bgc_data(type='test')

# coreDS = coreDS.reset_coords(['yearday', 'latitude', 'longitude', 'datetime'])
# coreDS_test = coreDS_test.reset_coords(['yearday', 'latitude', 'longitude', 'datetime', 'year', 'month', 'day'])

# fullDS = xr.merge([coreDS, coreDS_test, bgcDS_test])
# fullINDEX = pd.concat([coreINDEX.to_dataframe().reset_index(), 
#                        coreINDEX_test.to_dataframe().reset_index(),
#                        bgcINDEX_test.to_dataframe().reset_index()],axis=0)
# fullINDEX = (fullINDEX.dropna(subset=['profid']) #, 'pressure'])
#             .set_index(['profid'])
#             .to_xarray()
#             .drop_duplicates('profid', keep='first'))
# fullINDEX

<xarray.Dataset>
Dimensions:           (profid: 356970)
Coordinates:
  * profid            (profid) object '1900410_id260' ... '7902133_testid004'
Data variables: (12/41)
    pressure          (profid) float64 6.4 7.0 6.0 6.6 5.9 ... nan nan nan nan
    wmoid             (profid) object 1900410.0 1900410.0 ... '7902133'
    latitude          (profid) float64 -40.36 -40.11 -40.25 ... -49.19 -49.87
    longitude         (profid) float64 95.36 96.08 96.68 ... 266.8 250.3 250.6
    datetime          (profid) object '2014-01-02 02:34:12.000000000' ... 202...
    yearday           (profid) float64 1.107 11.27 21.44 31.61 ... nan nan nan
    ...                ...
    pCO2_pHbias3      (profid) float64 nan nan nan nan ... 470.4 453.4 433.5
    pCO2_pHbias5      (profid) float64 nan nan nan nan ... 467.9 451.1 431.3
    pCO2_pHbias3_pK1  (profid) float64 nan nan nan nan ... 460.8 444.1 424.7
    pCO2_pHbias5_pK1  (profid) float64 nan nan nan nan ... 458.4 441.8 422.5
    pco2_ocean        (profid) float64 nan nan nan nan ... 458.4 441.8 422.5
    delta_pco2        (profid) float64 nan nan nan nan ... 44.01 44.07 10.37

In [35]:
socat_test

,cruiseid,datetime,longitude,latitude,linear_time,nearest_profid,prof_datetime,prof_lat,prof_lon,yd_sep,...,adt,wind_speed,sea_ice,atmos_pres_Pa,atmos_pres_atm,vapor_pres_atm,fco2rec,pco2_atmos,pco2_ocean,delta_pco2
6806,096U20240105,2024-01-05 12:26:19,145.71705,-44.72705,3656.518275,6903215_id255,2024-01-10,-43.790252,143.833693,5.199780,...,0.6885,4.776035,0.0,102460.0,1.011202,0.018539,324.1865,414.543412,325.334404,-89.209007
6807,096U20240105,2024-01-06 12:06:31,142.71100,-46.66590,3657.504525,5905501_id132,2024-01-04,-45.779513,143.122653,1.525359,...,0.6515,3.548280,0.0,101470.0,1.001431,0.013753,352.3960,412.409016,353.719551,-58.689465
6808,096U20240105,2024-01-07 11:57:49,145.40880,-49.87020,3658.498484,5906209_id143,2024-01-05,-50.733000,147.216000,1.824664,...,-0.0895,11.435872,0.0,101160.0,0.998372,0.012037,373.2970,411.785824,374.735959,-37.049865
6809,096U20240105,2024-01-08 12:03:51,148.25500,-54.51200,3659.502674,2903453_id028,2024-01-03,-54.371100,146.883700,4.520191,...,-0.5517,7.063024,0.0,100740.0,0.994226,0.008728,398.1170,411.410734,399.749630,-11.661104
6810,096U20240105,2024-01-09 13:07:23,149.50530,-59.49740,3660.546794,7900637_id200,2024-01-16,-59.663702,149.284939,6.884248,...,-1.0160,18.026432,0.0,100070.0,0.987614,0.006118,360.2610,409.753503,361.840872,-47.912631
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7235,WFCH20240206,2024-02-20 03:16:55,-136.38265,-73.29205,3702.136748,5906556_id041,2024-02-20,-70.554700,-135.543900,0.001024,...,-1.1179,6.558754,0.0,100310.0,0.989983,0.005426,250.8455,411.097051,251.970483,-159.126567
7236,WFCH20240206,2024-02-23 17:32:21,-99.91180,-70.46775,3705.730799,3902325_id095,2024-02-24,-67.503000,-103.499490,0.303779,...,-1.0880,12.358945,0.0,97870.0,0.965902,0.005534,398.7545,400.987695,400.536321,-0.451374
7237,WFCH20240206,2024-03-01 11:50:45,-65.76490,-60.64345,3712.493576,4902638_id004,2024-03-05,-60.798679,-64.430321,4.092535,...,-0.8436,8.016185,0.0,97710.0,0.964323,0.007141,425.1250,399.609350,426.936046,27.326695
7238,WFCH20240303,2024-03-06 11:26:10,-55.87635,-44.48470,3717.476505,3901565_id124,2024-03-12,-45.024100,-57.620200,6.053501,...,-0.0622,2.491040,0.0,102080.0,1.007451,0.016576,338.7715,413.803880,339.998145,-73.805735
7239,WFCH20240303,2024-03-07 11:25:53,-52.15820,-39.50590,3718.476308,5906541_id048,2024-03-08,-38.354200,-50.462200,0.708038,...,0.6629,8.611823,0.0,102120.0,1.007846,0.024252,368.1940,411.039605,369.429506,-41.610099

In [14]:
PCM_finder

,1,2,3,4,5,6,class_assign,prof_datetag
profid,,,,,,,,
5902383_id007,7.373051e-05,4.133867e-03,9.957923e-01,3.076116e-10,5.018355e-15,6.945239e-08,3,5902383_20150307
5904528_id145,6.750567e-04,2.246674e-21,1.195361e-22,9.854693e-05,9.992264e-01,2.169307e-08,5,5904528_20170830
5901647_id301,1.930536e-03,4.319632e-21,1.407406e-14,8.588624e-08,9.980694e-01,1.913745e-09,5,5901647_20160331
1901831_id012,1.295108e-01,1.057091e-12,8.246486e-01,6.834287e-11,4.584066e-02,4.816086e-09,3,1901831_20160517
5905426_id081,2.738858e-02,1.838218e-47,1.640856e-112,8.609365e-01,4.912203e-08,1.116749e-01,4,5905426_20210126
...,...,...,...,...,...,...,...,...
7900067_id171,2.292326e-03,2.370784e-13,9.963080e-01,2.430801e-09,1.399710e-03,2.981814e-10,3,7900067_20170929
5904266_id243,4.842177e-03,4.126820e-25,2.298051e-38,1.502795e-02,9.801275e-01,2.345825e-06,5,5904266_20200603
1901308_id087,9.297391e-01,4.272232e-16,7.077842e-03,6.741009e-10,6.318295e-02,5.828921e-08,1,1901308_20151104
3901895_id063,1.035446e-06,1.576697e-05,9.999832e-01,2.352745e-11,3.100185e-15,5.754476e-10,3,3901895_20181227
5901639_id276,3.717274e-10,8.494061e-162,0.000000e+00,7.859665e-14,1.593713e-41,1.000000e+00,6,5901639_20150530

# Classify floats (bgcArgo_trainval, bgcArgo_test, coreArgo_application)

In [15]:
# Add class assignments (will not drop nans yet)
floatDF = mod_pcm.add_class_assignments(bgcArgo_trainval, PCM_finder, n_gmm, profid_col='profid')
floatDF['prof_datetag'] = floatDF['prof_datetag'].astype(str)
floatDF_filled = mod_pcm.fill_missing_float_classes(floatDF.set_index('profid'), n_gmm=n_gmm)



# coreArgo_application['prof_datetag'] = coreArgo_application['profid'].apply(lambda x: str(x).split('_')[0])
# coreArgo_application['prof_datetag'] = coreArgo_application.apply(lambda row: row.prof_datetag + '_' + row.datetime.strftime('%Y%m%d'), axis=1)

Initially missing class assignments for 267 profiles, searching to fill with adjacent datetags...
Filled in 227 missing assignments using adjacent profiles
Total 10781 valid profiles

In [16]:
testDF = mod_pcm.add_class_assignments(bgcArgo_test, PCM_finder, n_gmm, profid_col='profid')
testDF['prof_datetag'] = testDF['prof_datetag'].astype(str)
testDF_filled = mod_pcm.fill_missing_float_classes(testDF.set_index('profid'), n_gmm=n_gmm)

Initially missing class assignments for 6 profiles, searching to fill with adjacent datetags...
Filled in 4 missing assignments using adjacent profiles
Total 2111 valid profiles

In [17]:
coreDF = mod_pcm.add_class_assignments(coreArgo_application, PCM_finder, n_gmm, profid_col='profid')
coreDF = (mod_prep.index_by_prof_datetag(coreDF)
                .reset_index().set_index('profid') # add prof_datetag as column so you can fill in 
)
coreDF_filled = mod_pcm.fill_missing_float_classes(coreDF, n_gmm=n_gmm)

Initially missing class assignments for 9994 profiles, searching to fill with adjacent datetags...
Filled in 6595 missing assignments using adjacent profiles
Total 325539 valid profiles

In [18]:
floatDF_filled

,wmoid,prof_datetag,datetime,latitude,longitude,ydcos,ydsin,year,month,day,...,pco2_atmos,pco2_ocean,delta_pco2,class1_prob,class2_prob,class3_prob,class4_prob,class5_prob,class6_prob,class_assign
profid,,,,,,,,,,,,,,,,,,,,,
5904187_id002,5904187,5904187_20140424,2014-04-24 01:35:59.999999,-45.027,209.980,-0.365551,0.930791,2014,4,24,...,382.385383,359.594018,-22.791365,9.758730e-01,6.771827e-31,5.462091e-52,6.089942e-06,2.376282e-02,3.580515e-04,1.0
5904187_id003,5904187,5904187_20140429,2014-04-29 10:21:59.999998,-44.925,209.465,-0.449781,0.893139,2014,4,29,...,392.294217,356.315818,-35.978399,9.238084e-01,5.817722e-31,4.957111e-52,3.095494e-05,7.580063e-02,3.600040e-04,1.0
5904187_id004,5904187,5904187_20140504,2014-05-04 17:40:00.000001,-45.037,209.571,-0.529291,0.848440,2014,5,4,...,390.099938,358.544402,-31.555536,9.934598e-01,1.006894e-30,7.325152e-53,4.700703e-05,5.849025e-03,6.441229e-04,1.0
5904187_id005,5904187,5904187_20140510,2014-05-10 00:45:59.999996,-44.769,209.377,-0.604283,0.796770,2014,5,10,...,386.600808,360.784113,-25.816695,9.401430e-01,1.576493e-30,1.061440e-51,6.318082e-05,5.936080e-02,4.330044e-04,1.0
5904187_id006,5904187,5904187_20140515,2014-05-15 07:09:00.000005,-44.989,209.152,-0.673884,0.738837,2014,5,15,...,393.854081,355.840425,-38.013657,5.311371e-01,5.838354e-30,6.063980e-51,1.815710e-03,4.666731e-01,3.740118e-04,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5906583_id030,5906583,5906583_20231110,2023-11-10 05:56:00.000004,-62.603,163.310,0.622491,-0.782627,2023,11,10,...,411.476586,422.057030,10.580444,1.409867e-12,9.969751e-01,3.024935e-03,2.198968e-19,1.842722e-51,7.587658e-10,2.0
5906583_id031,5906583,5906583_20231120,2023-11-20 12:59:00.000000,-62.689,162.887,0.750620,-0.660735,2023,11,20,...,416.243436,408.826105,-7.417331,1.795546e-12,9.986053e-01,1.394747e-03,9.730388e-19,1.965019e-49,4.395580e-10,2.0
5906583_id032,5906583,5906583_20231130,2023-11-30 19:55:59.999998,-62.720,162.534,0.855236,-0.518240,2023,11,30,...,410.705222,401.951619,-8.753604,1.263083e-12,9.999679e-01,3.206699e-05,2.675566e-19,2.430254e-51,2.551384e-10,2.0
5906583_id033,5906583,5906583_20231211,2023-12-11 04:32:00.000003,-62.700,162.647,0.933550,-0.358446,2023,12,11,...,407.573351,398.963470,-8.609881,2.128656e-12,9.999275e-01,7.254493e-05,1.916841e-19,4.061135e-50,2.616981e-10,2.0
5906583_id034,5906583,5906583_20231221,2023-12-21 11:39:00.000005,-62.655,163.179,0.982103,-0.188346,2023,12,21,...,393.063566,393.863441,0.799875,2.076609e-11,9.999779e-01,2.214751e-05,3.306068e-20,1.368507e-48,2.689172e-10,2.0

In [19]:
testDF_filled

,wmoid,prof_datetag,datetime,latitude,longitude,ydcos,ydsin,year,month,day,...,pco2_atmos,pco2_ocean,delta_pco2,class1_prob,class2_prob,class3_prob,class4_prob,class5_prob,class6_prob,class_assign
profid,,,,,,,,,,,,,,,,,,,,,
1902494_testid005,1902494,1902494_20240414,2024-04-14 01:05:59.999995,-46.051,8.418,-0.208893,0.977938,2024,4,14,...,412.286438,372.484853,-39.801585,0.930630,6.495072e-17,1.783287e-04,4.032153e-11,0.069192,1.412735e-08,1.0
1902494_testid006,1902494,1902494_20240415,2024-04-15 00:34:59.999996,-46.079,8.489,-0.225324,0.974284,2024,4,15,...,411.843348,377.974947,-33.868401,0.818859,1.128807e-16,1.904403e-04,4.985432e-11,0.180951,1.454873e-08,1.0
1902494_testid006,1902494,1902494_20240415,2024-04-15 23:15:59.999996,-46.119,8.556,-0.241134,0.970492,2024,4,15,...,412.895518,377.332637,-35.562880,0.818859,1.128807e-16,1.904403e-04,4.985432e-11,0.180951,1.454873e-08,1.0
1902494_testid008,1902494,1902494_20240416,2024-04-16 21:53:00.000002,-46.144,8.612,-0.256834,0.966456,2024,4,16,...,413.568473,374.948496,-38.619977,0.545617,2.225389e-16,1.767743e-04,2.426274e-10,0.454206,1.378105e-08,1.0
1902494_testid009,1902494,1902494_20240417,2024-04-17 20:03:00.000003,-46.172,8.652,-0.272156,0.962253,2024,4,17,...,413.207793,377.168868,-36.038925,0.854353,2.043213e-17,5.953297e-04,2.391447e-11,0.145051,1.015483e-08,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7902134_testid001,7902134,7902134_20241202,2024-12-02 05:03:00.000003,-43.610,266.023,0.873645,-0.486564,2024,12,2,...,411.264266,407.282639,-3.981627,0.516881,6.750933e-24,4.539465e-18,2.881916e-08,0.483119,2.755023e-07,1.0
7902134_testid002,7902134,7902134_20241212,2024-12-12 10:44:59.999997,-43.667,266.415,0.945378,-0.325975,2024,12,12,...,413.797331,445.396625,31.599294,0.724459,1.996108e-24,8.517416e-19,6.323853e-09,0.275540,2.967351e-07,1.0
7902134_testid003,7902134,7902134_20241222,2024-12-22 16:30:59.999996,-43.583,266.845,0.987875,-0.155254,2024,12,22,...,414.398989,458.409796,44.010807,0.408370,1.343688e-23,4.703401e-18,1.561296e-08,0.591629,2.208024e-07,5.0
7902133_testid002,7902133,7902133_20241207,2024-12-07 07:07:59.999998,-49.189,250.268,0.912825,-0.408351,2024,12,7,...,397.741042,441.809882,44.068841,0.054098,3.324741e-21,3.850767e-21,7.195633e-06,0.945894,4.168298e-07,5.0
7902133_testid004,7902133,7902133_20241227,2024-12-27 19:49:59.999999,-49.872,250.617,0.997723,-0.067444,2024,12,27,...,412.110823,422.480054,10.369231,0.024111,7.878232e-22,8.832559e-22,4.912859e-06,0.975884,1.664191e-07,5.0

In [20]:
coreDF_filled

,level_0,index,pressure,wmoid,latitude,longitude,datetime,yearday,CT,SA,...,vapor_pres_atm,pco2_atmos,class1_prob,class2_prob,class3_prob,class4_prob,class5_prob,class6_prob,class_assign,prof_datetag
profid,,,,,,,,,,,,,,,,,,,,,
1900410_id260,0,0,6.4,1900410.0,-40.358000,95.357000,2014-01-02 02:34:12,1.107083,12.707135,35.034611,...,0.014217,392.043076,0.000041,6.578699e-52,7.239645e-118,9.984696e-01,6.434109e-09,1.489595e-03,4.0,1900410_20140102
1900410_id261,1,1,7.0,1900410.0,-40.109000,96.083000,2014-01-12 06:35:16,11.274491,13.136123,35.033602,...,0.014621,391.075263,0.000058,3.311144e-53,2.316064e-122,9.971936e-01,4.474759e-09,2.748832e-03,4.0,1900410_20140112
1900410_id262,2,2,6.0,1900410.0,-40.247000,96.676000,2014-01-22 10:36:20,21.441898,14.351957,34.975328,...,0.015823,386.076861,0.000178,2.452166e-55,2.745927e-131,9.658792e-01,9.623468e-12,3.394279e-02,4.0,1900410_20140122
1900410_id263,3,3,6.6,1900410.0,-40.371000,96.900000,2014-02-01 14:33:32,31.606620,13.675696,35.015520,...,0.015145,388.967172,0.000090,1.420563e-55,9.945068e-131,9.888316e-01,2.199927e-11,1.107836e-02,4.0,1900410_20140201
1900410_id264,4,4,5.9,1900410.0,-40.340000,96.969000,2014-02-11 18:47:10,41.782755,13.617688,35.019535,...,0.015088,393.248530,0.000078,4.677140e-56,3.751441e-132,9.878963e-01,3.942727e-11,1.202583e-02,4.0,1900410_20140211
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7901011_id001,328933,328933,10.6,7901011.0,-54.642010,-51.690847,2023-11-11 21:57:00,3601.914583,3.979210,34.266818,...,0.007856,405.579794,0.021164,1.733015e-07,9.787968e-01,2.329387e-07,3.890900e-05,6.986966e-08,3.0,7901011_20231111
7901011_id002,328934,328934,3.1,7901011.0,-53.820388,-49.906383,2023-11-23 17:01:30,3613.709375,4.143979,34.242454,...,0.007947,411.912454,0.080570,5.755100e-09,7.538960e-01,1.852623e-06,1.655317e-01,1.397941e-07,3.0,7901011_20231123
7901011_id003,328935,328935,2.8,7901011.0,-53.981737,-48.127877,2023-12-03 12:41:30,3623.528819,3.454201,34.212383,...,0.007570,405.887082,0.001185,1.214708e-06,9.988085e-01,9.651224e-07,4.287417e-06,4.227167e-08,3.0,7901011_20231203
7901011_id004,328936,328936,3.1,7901011.0,-52.839405,-48.947265,2023-12-13 07:27:30,3633.310764,3.677531,34.179080,...,0.007691,407.217298,0.001621,1.548750e-09,9.972853e-01,1.268755e-08,1.093702e-03,4.325349e-09,3.0,7901011_20231213
7901011_id005,328937,328937,2.9,7901011.0,-51.787013,-46.818465,2023-12-23 02:42:30,3643.112847,4.815987,34.162907,...,0.008330,408.536567,0.003311,5.927885e-07,9.966703e-01,7.642679e-07,1.678202e-05,9.303790e-08,3.0,7901011_20231223

In [ ]:
# # bgcArgo_trainval = bgcArgo_trainval.copy(); socat_trainval = socat_trainval.copy()
# for k in range(1, n_gmm+1):
#     bgcArgo_trainval['class' + str(k) + '_prob'] = bgcArgo_trainval['profid'].apply(lambda x: PCM_finder.loc[x, str(k)] if x in PCM_finder.index else np.nan)
#     socat_trainval['class' + str(k) + '_prob'] = socat_trainval['nearest_profid'].apply(lambda x: PCM_finder.loc[x, str(k)] if x in PCM_finder.index else np.nan)

# bgcArgo_trainval['class_assign'] = (bgcArgo_trainval['profid'].apply(lambda x: PCM_finder.loc[x, 'class_assign'] if x in PCM_finder.index else np.nan))
# socat_trainval['class_assign'] = (socat_trainval['nearest_profid'].apply(lambda x: PCM_finder.loc[x, 'class_assign'] if x in PCM_finder.index else np.nan))

# bgcArgo_trainval = bgcArgo_trainval.dropna(subset=['class_assign'])
# socat_trainval = socat_trainval.dropna(subset=['class_assign'])

In [ ]:

# [bgcArgo_trainval, bgcArgo_test, socat_trainval, coreArgo_application] = loader.import_p1_processed()
# [Y_gmm, allprobs] = loader.import_p2_clustered(pcm_params = pcm_params)

# PCM_finder = allprobs.set_index('profid') # temp object to search
# PCM_finder['class_assign'] = Y_gmm.loc[PCM_finder.index, 'class']

# # Add clustering probabilities to the float DF

# # if '0' in PCM_finder.columns: # shouldn't need anymore. fixed in 2.1
# #    PCM_finder = PCM_finder.rename(columns = {str(k): k+1 for k in np.arange(n_gmm-1, -1, -1)})
# # print(PCM_finder.columns)

# # bgcArgo_trainval = bgcArgo_trainval.copy(); socat_trainval = socat_trainval.copy()
# for k in range(1, n_gmm+1):
#     bgcArgo_trainval['class' + str(k) + '_prob'] = bgcArgo_trainval['profid'].apply(lambda x: PCM_finder.loc[x, str(k)] if x in PCM_finder.index else np.nan)
#     socat_trainval['class' + str(k) + '_prob'] = socat_trainval['nearest_profid'].apply(lambda x: PCM_finder.loc[x, str(k)] if x in PCM_finder.index else np.nan)

# bgcArgo_trainval['class_assign'] = (bgcArgo_trainval['profid'].apply(lambda x: PCM_finder.loc[x, 'class_assign'] if x in PCM_finder.index else np.nan))
# socat_trainval['class_assign'] = (socat_trainval['nearest_profid'].apply(lambda x: PCM_finder.loc[x, 'class_assign'] if x in PCM_finder.index else np.nan))

# bgcArgo_trainval = bgcArgo_trainval.dropna(subset=['class_assign'])
# socat_trainval = socat_trainval.dropna(subset=['class_assign'])

# Classify SOCAT

In [36]:
shipDF = mod_pcm.add_class_assignments(socat_trainval, PCM_finder, n_gmm, profid_col='nearest_profid')
shipDF['sample_datetag'] = shipDF['cruiseid'] + '_' + shipDF['datetime'].dt.strftime('%Y%m%d%H')
shipDF_filled = mod_pcm.fill_missing_ship_classes(shipDF.set_index('sample_datetag'), n_gmm)

Filled in 165 missing assignments using adjacent profiles
Total 6651 valid profiles

In [37]:
shipDF_test = mod_pcm.add_class_assignments(socat_test, PCM_finder, n_gmm, profid_col='nearest_profid')
shipDF_test['sample_datetag'] = shipDF_test['cruiseid'] + '_' + shipDF_test['datetime'].dt.strftime('%Y%m%d%H')
shipDF_test_filled = mod_pcm.fill_missing_ship_classes(shipDF_test.set_index('sample_datetag'), n_gmm)

Filled in 16 missing assignments using adjacent profiles
Total 417 valid profiles

In [170]:
# missingClasses = shipDF[shipDF['class_assign'].isna()]  #.reset_index().set_index('sample_datetag')
# samplesReplaced = []; 

# for sdt, obs in missingClasses.iterrows(): # for sample_datetag, row ... 
#     same_cruise = shipDF[shipDF['cruiseid'] == obs.cruiseid].copy()

#     if len(same_cruise)>0:
#         same_cruise['timediff'] = same_cruise.apply(lambda row: abs((row.datetime - (obs.datetime)).days), axis=1)
#         valid = same_cruise[same_cruise.timediff<1.5].copy()
    
#         if valid.class_assign.nunique() == 1:

#             shipDF.loc[sdt, 'class_assign'] = valid['class_assign'].values[0]
#             for k in range(1, n_gmm+1):
#                 shipDF.loc[sdt,'class' + str(k) + '_prob'] = valid['class' + str(k) + '_prob'].values[0]
#             samplesReplaced.append(sdt)

# shipDF = shipDF.dropna(subset='class_assign')
# print('Filled in ' + str(len(samplesReplaced)) + ' missing assignments using adjacent profiles')
# print('Total ' + str(len(shipDF)) + ' valid profiles')

Filled in 163 missing assignments using adjacent profiles
Total 6139 valid profiles

In [ ]:
# moved to mod_pcm
# def fill_missing_ship_classes(shipDF, n_gmm):
#     missingClasses = shipDF[shipDF['class_assign'].isna()]  #.reset_index().set_index('sample_datetag')
#     samplesReplaced = []; 

#     for sdt, obs in missingClasses.iterrows(): # for sample_datetag, row ... 
#         same_cruise = shipDF[shipDF['cruiseid'] == obs.cruiseid].copy()

#         if len(same_cruise)>0:
#             same_cruise['timediff'] = same_cruise.apply(lambda row: abs((row.datetime - (obs.datetime)).days), axis=1)
#             valid = same_cruise[same_cruise.timediff<2].copy()
        
#             if valid.class_assign.nunique() == 1:

#                 shipDF.loc[sdt, 'class_assign'] = valid['class_assign'].values[0]
#                 for k in range(1, n_gmm+1):
#                     shipDF.loc[sdt,'class' + str(k) + '_prob'] = valid['class' + str(k) + '_prob'].values[0]
#                 samplesReplaced.append(sdt)

#     shipDF = shipDF.dropna(subset='class_assign')
#     print('Filled in ' + str(len(samplesReplaced)) + ' missing assignments using adjacent profiles')
#     print('Total ' + str(len(shipDF)) + ' valid profiles')

#     return shipDF

In [38]:
shipDF_filled

,cruiseid,datetime,longitude,latitude,linear_time,nearest_profid,prof_datetime,prof_lat,prof_lon,yd_sep,...,pco2_atmos,pco2_ocean,delta_pco2,class1_prob,class2_prob,class3_prob,class4_prob,class5_prob,class6_prob,class_assign
sample_datetag,,,,,,,,,,,,,,,,,,,,,
06AQ20131221_2014010211,06AQ20131221,2014-01-02 11:36:53,-24.64215,-73.72590,1.483947,7900378_id041,2014-01-09,-71.616580,-22.823985,6.720278,...,385.975982,343.219907,-42.756075,7.807649e-13,9.999457e-01,5.433213e-05,9.671966e-21,3.379425e-54,7.100050e-10,2.0
06AQ20131221_2014011011,06AQ20131221,2014-01-10 11:59:17,-36.40135,-77.10035,9.499502,7900378_id041,2014-01-09,-71.616580,-22.823985,1.295284,...,385.238844,367.543164,-17.695680,7.807649e-13,9.999457e-01,5.433213e-05,9.671966e-21,3.379425e-54,7.100050e-10,2.0
06AQ20131221_2014011611,06AQ20131221,2014-01-16 11:48:03,-38.14620,-77.89910,15.491701,7900378_id042,2014-01-19,-71.682778,-23.213771,2.700012,...,383.955134,276.631562,-107.323573,5.098094e-13,9.999998e-01,1.988611e-07,9.951832e-24,1.903841e-59,5.863097e-10,2.0
06AQ20131221_2014011707,06AQ20131221,2014-01-17 07:05:05,-38.94590,-77.60800,16.295197,7900378_id042,2014-01-19,-71.682778,-23.213771,1.896510,...,384.469845,376.886195,-7.583650,5.098094e-13,9.999998e-01,1.988611e-07,9.951832e-24,1.903841e-59,5.863097e-10,2.0
06AQ20131221_2014012211,06AQ20131221,2014-01-22 11:58:20,-28.47890,-74.55740,21.498843,7900378_id043,2014-01-29,-71.743994,-23.090656,6.695984,...,390.543232,300.131879,-90.411353,2.094933e-13,1.000000e+00,1.585576e-14,5.148393e-32,1.086498e-75,5.211504e-10,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WFCH20231129_2023121112,WFCH20231129,2023-12-11 12:01:49,-65.78520,-62.17040,3631.501262,5906560_id033,2023-12-09,-62.110100,-69.038300,1.986481,...,403.206980,401.289162,-1.917818,7.532060e-06,1.265428e-05,9.999798e-01,4.062642e-10,4.397677e-14,1.371565e-09,3.0
WFCH20231129_2023121210,WFCH20231129,2023-12-12 10:01:29,-66.72210,-56.71340,3632.417697,7900804_id039,2023-12-05,-60.427280,-72.163230,6.662627,...,401.967338,383.808271,-18.159066,2.026639e-01,4.157412e-08,5.659059e-01,1.003689e-06,2.314288e-01,3.297850e-07,3.0
WFCH20231213_2023121411,WFCH20231213,2023-12-14 11:55:42,-66.73620,-56.98710,3634.497014,5906560_id033,2023-12-09,-62.110100,-69.038300,4.982234,...,403.130758,388.731630,-14.399128,7.532060e-06,1.265428e-05,9.999798e-01,4.062642e-10,4.397677e-14,1.371565e-09,3.0
WFCH20231227_2023122917,WFCH20231227,2023-12-29 17:03:41,-64.97110,-56.32710,3649.710891,6903769_id146,2024-01-04,-58.725878,-69.085745,5.560289,...,402.644772,388.110232,-14.534540,5.531534e-02,4.119254e-09,3.848707e-01,2.190679e-06,5.598117e-01,9.635031e-08,5.0
WFCH20231227_2023123012,WFCH20231227,2023-12-30 12:34:13,-59.07820,-60.58375,3650.523762,5906560_id035,2023-12-30,-62.152700,-68.108100,0.373154,...,397.967259,415.065202,17.097943,5.531534e-02,4.119254e-09,3.848707e-01,2.190679e-06,5.598117e-01,9.635031e-08,5.0

# Optional save

In [24]:
datetag

# P2_socat-trainvalDF_class-gapfilled_

'20260327'

In [39]:
shipDF_filled['platform'] = np.tile('socatv2025', len(shipDF_filled))
shipDF_test_filled['platform'] = np.tile('socatv2025', len(shipDF_test_filled))


save = True
if save:
    shipDF_filled.to_csv(save_path + 'P2_socat-trainvalDF_class-gapfilled_' + pcm_params + '_acc' + datetag + '.csv')
    shipDF_test_filled.to_csv(save_path + 'P2_socat-testDF_class-gapfilled_' + pcm_params + '_acc' + datetag + '.csv')
    print('Saved shipDF_filled to ' + save_path + 'P2_socat-trainvalDF_class-gapfilled_' + pcm_params + '_acc' + datetag + '.csv')
    print(datetime.now().strftime('%Y-%m-%d %H:%M:%S'))

Saved shipDF_filled to ../working-vars/regression/P2-clustered/pc8_gmm6/P2_socat-trainvalDF_class-gapfilled_pc8_gmm6_acc20260327.csv
2026-03-27 13:50:29

In [29]:
shipDF_filled

,cruiseid,datetime,longitude,latitude,linear_time,nearest_profid,prof_datetime,prof_lat,prof_lon,yd_sep,...,pco2_ocean,delta_pco2,class1_prob,class2_prob,class3_prob,class4_prob,class5_prob,class6_prob,class_assign,platform
sample_datetag,,,,,,,,,,,,,,,,,,,,,
06AQ20131221_2014010211,06AQ20131221,2014-01-02 11:36:53,-24.64215,-73.72590,1.483947,7900378_id041,2014-01-09,-71.616580,-22.823985,6.720278,...,343.219907,-42.756075,7.807649e-13,9.999457e-01,5.433213e-05,9.671966e-21,3.379425e-54,7.100050e-10,2.0,socatv2025
06AQ20131221_2014011011,06AQ20131221,2014-01-10 11:59:17,-36.40135,-77.10035,9.499502,7900378_id041,2014-01-09,-71.616580,-22.823985,1.295284,...,367.543164,-17.695680,7.807649e-13,9.999457e-01,5.433213e-05,9.671966e-21,3.379425e-54,7.100050e-10,2.0,socatv2025
06AQ20131221_2014011611,06AQ20131221,2014-01-16 11:48:03,-38.14620,-77.89910,15.491701,7900378_id042,2014-01-19,-71.682778,-23.213771,2.700012,...,276.631562,-107.323573,5.098094e-13,9.999998e-01,1.988611e-07,9.951832e-24,1.903841e-59,5.863097e-10,2.0,socatv2025
06AQ20131221_2014011707,06AQ20131221,2014-01-17 07:05:05,-38.94590,-77.60800,16.295197,7900378_id042,2014-01-19,-71.682778,-23.213771,1.896510,...,376.886195,-7.583650,5.098094e-13,9.999998e-01,1.988611e-07,9.951832e-24,1.903841e-59,5.863097e-10,2.0,socatv2025
06AQ20131221_2014012211,06AQ20131221,2014-01-22 11:58:20,-28.47890,-74.55740,21.498843,7900378_id043,2014-01-29,-71.743994,-23.090656,6.695984,...,300.131879,-90.411353,2.094933e-13,1.000000e+00,1.585576e-14,5.148393e-32,1.086498e-75,5.211504e-10,2.0,socatv2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WFCH20231129_2023121112,WFCH20231129,2023-12-11 12:01:49,-65.78520,-62.17040,3631.501262,5906560_id033,2023-12-09,-62.110100,-69.038300,1.986481,...,401.289162,-1.917818,7.532060e-06,1.265428e-05,9.999798e-01,4.062642e-10,4.397677e-14,1.371565e-09,3.0,socatv2025
WFCH20231129_2023121210,WFCH20231129,2023-12-12 10:01:29,-66.72210,-56.71340,3632.417697,7900804_id039,2023-12-05,-60.427280,-72.163230,6.662627,...,383.808271,-18.159066,2.026639e-01,4.157412e-08,5.659059e-01,1.003689e-06,2.314288e-01,3.297850e-07,3.0,socatv2025
WFCH20231213_2023121411,WFCH20231213,2023-12-14 11:55:42,-66.73620,-56.98710,3634.497014,5906560_id033,2023-12-09,-62.110100,-69.038300,4.982234,...,388.731630,-14.399128,7.532060e-06,1.265428e-05,9.999798e-01,4.062642e-10,4.397677e-14,1.371565e-09,3.0,socatv2025
WFCH20231227_2023122917,WFCH20231227,2023-12-29 17:03:41,-64.97110,-56.32710,3649.710891,6903769_id146,2024-01-04,-58.725878,-69.085745,5.560289,...,388.110232,-14.534540,5.531534e-02,4.119254e-09,3.848707e-01,2.190679e-06,5.598117e-01,9.635031e-08,5.0,socatv2025
WFCH20231227_2023123012,WFCH20231227,2023-12-30 12:34:13,-59.07820,-60.58375,3650.523762,5906560_id035,2023-12-30,-62.152700,-68.108100,0.373154,...,415.065202,17.097943,5.531534e-02,4.119254e-09,3.848707e-01,2.190679e-06,5.598117e-01,9.635031e-08,5.0,socatv2025

In [26]:
floatDF_filled['platform'] = np.tile('bgcArgo', len(floatDF_filled))
testDF_filled['platform'] = np.tile('bgcArgo', len(testDF_filled))
# coreDF_filled['platform'] = np.tile('coreArgo', len(coreDF_filled))
shipDF_filled['platform'] = np.tile('socatv2024', len(shipDF_filled))

In [27]:
save = True
if save:
    floatDF_filled.to_csv(save_path + 'P2_bgcArgo-trainvalDF_class-gapfilled_' + pcm_params + '_acc' + datetag + '.csv')
    testDF_filled.to_csv(save_path + 'P2_bgcArgo-testDF_class-gapfilled_' + pcm_params + '_acc' + datetag + '.csv')
    # coreDF_filled.to_csv(save_path + 'P2_coreArgo-applicationDF_class-gapfilled_' + pcm_params + '_acc' + datetag + '.csv')
    shipDF_filled.to_csv(save_path + 'P2_socat-trainvalDF_class-gapfilled_' + pcm_params + '_acc' + datetag + '.csv')

    print('Saved floatDF_filled to ' + save_path + 'P2_bgcArgo-trainvalDF_class-gapfilled_' + pcm_params + '_acc' + datetag + '.csv')
    print(datetime.now().strftime('%Y-%m-%d %H:%M:%S'))

Saved floatDF_filled to ../working-vars/regression/P2-clustered/pc8_gmm6/P2_bgcArgo-trainvalDF_class-gapfilled_pc8_gmm6_acc20260327.csv
2026-03-27 13:34:42

In [ ]:
# floatDF_filled = pd.read_csv(save_path + 'P2_bgcArgo-trainvalDF_class-gapfilled_' + pcm_params + '_acc' + datetag + '.csv', index_col=0)
# testDF_filled = pd.read_csv(save_path + 'P2_bgcArgo-testDF_class-gapfilled_' + pcm_params + '_acc' + datetag + '.csv', index_col=0)
# coreDF_filled = pd.read_csv(save_path + 'P2_coreArgo-applicationDF_class-gapfilled_' + pcm_params + '_acc' + datetag + '.csv', index_col=0)
# shipDF_filled = pd.read_csv(save_path + 'P2_socat-trainvalDF_class-gapfilled_' + pcm_params + '_acc' + datetag + '.csv', index_col=0)